import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/header/Header";

import { Inter, Barlow_Condensed } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] });

const barlow = Barlow_Condensed({
  subsets: ['latin'],
  weight: "500"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="en">
      <body className={barlow.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}